spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always